json.id @seizure.id
json.date @seizure.date
json.startTime @seizure.start_time
json.duration @seizure.duration
json.category @seizure.category
json.triggers @seizure.triggers
json.descriptions @seizure.descriptions
json.postEvents @seizure.post_events
json.customComment @seizure.custom_comment
